version: '3.8'

services:
  database:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: adminapp
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: adminpass
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    environment:
      DB_HOST: database
      DB_USER: adminuser
      DB_PASS: adminpass
      DB_NAME: adminapp
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
