name: Build & Push Microservices to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_backend:v1.0.1 ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/flask_backend:v1.0.1

    - name: Build & Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx_frontend:v1.0.1 ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx_frontend:v1.0.1

    - name: Push MySQL (Optional if using public image)
      run: |
        docker pull mysql:5.7
        docker tag mysql:5.7 ${{ secrets.DOCKER_USERNAME }}/mysql_db:v1.0.1
        docker push ${{ secrets.DOCKER_USERNAME }}/mysql_db:v1.0.1
